### ISSUE TITLE
弱弱的问一句 你的工程编译不过去啊

### ISSUE THREAD

**Issue by zjbbuaa0817** [GeneralSandman/TinyWeb#1]
我看makefile里面只是指定了各个lib名称，没有搜索路径，是不是要配置一下环境变量什么的

**Comment by ZgblKylin** [comment]
我看了下源码，许多文件都只有个架子，cc实现还没写，目前是组织了整体的文件结构，编译不过不奇怪

**Comment by GeneralSandman** [comment]
刚刚改了目录结构，累死了，makefile还没还回来，三天之内一定更改好，改好通知你们。带来不便，不要打我😂

**Comment by zput** [comment]
还是 不能通过，缺少 main.cc
