### ISSUE TITLE
分享下日志组件的心得吧

### ISSUE THREAD

**Issue by ZgblKylin** [GeneralSandman/TinyWeb#2]
大致看了下代码，文件结构和架构思路比较清晰，但因为大部分功能都还没完成，也看不出太多。
目前完成度比较高的是日志部分，正好我自己主要做的一个个人项目也是这个[log4qt](https://github.com/ZgblKylin/log4qt)，可以互相探讨下。

**事件循环**
首先，这个项目的核心功能，也是最先需要完成的（不包括日志一类辅助功能），应该是eventloop。
网络框架之所以在cpp框架里有如此重要的地位，不仅仅是因为这门语言的主流需求都需要一个网络库，更重要的是网络框架提供了完备的事件体系，以及与其配合的thread、timer等周边组件，而事件机制正是组织一个上规模的cpp应用的核心部分。
这部分我简单看了下eventloop和channel，感觉有一些可以深入的部分：
1. 目前的eventloop看起来主要是针对epool进行封装，那么主要处理的还是对外事件，缺乏进程内的更细分的事件管理。
2、事件处理通过回调进行，并且暂时没看到事件携带状态数据，所以灵活程度不够。
如果仅限于处理网络连接，那么可堪一用，但如果想进一步把更多功能纳入事件体系中，则需要一个足够开放的架构。
这方面，由于我还没拜读过muduo，个人感觉是可以参考Qt的实现，通过Event基类，以继承+虚函数形式封装不同类型的事件，然后通过eventloop进行分发。

**日志功能**
log已经算初步完成，可以使用，用作简单的调试记录已经可以，但有一些性能相关的细节需要考虑下。
1. Logger::getStream 中的enum分发，理论上应该选用switch而非连续的if else。虽然现代编译器上应该可以优化成一样，但从编码角度不应如此实现。
2. 日志记录为同步处理，缺少中间层
日志信息会在用户录入的同时直接通过ostream输出到文件中，这部分的性能开销涉及到I/O操作，是无法预估而且可能比较庞大的——在网络框架这类性能极端苛刻的场合，可能会影响到关键环节的运作。
建议加入中间层，用户录入数据由中间层转发至后台的日志处理组件，日志处理组件在独立线程中异步运行，来进行日志存储等工作。
并且，由于此项目是多进程设计，从这个角度也需要有一个独立的日志服务线程/进程来汇总记录日志，否则各个子进程的日志分别存储会很混乱，全存储到同一文件则涉及到繁琐的同步问题。
如果进行异步改造的话，就很依赖上一条提到的事件机制了。如我自己那个项目中，是基于Qt的信号槽机制进行分发。
3. 缺少日志过滤机制
为在多进程/线程的场合下高效调试，我们需要尽可能详细的debug日志。但为了性能，我们又必须在需要的时候可以关闭此类日志。
并且，通过预编译宏进行开关也不合适，因为这是静态的，如果程序在生产环境出问题了，我们应该能够在运行时动态开启debug日志进行检查。
此处我的实现方式，是在LOG宏的位置通过if进行过滤，未开启的日志分类不会进入if分支，于是不产生任何性能开销。

不过，我说的许多方面可能也不对，因为我并没有深入接触过任何一个网络框架，工作场合中用的大多是裸的socket、select、epoll一类，唯一了解多点的UDT也仅只是socket库。
而涉及事件体系的框架，深入了解过的也只有Qt一个。
所以可能有偏颇之处，希望能互相交流学习，我也正好有个机会从入门级别开始深入了解如何从0开始搭建网络框架。
如果我说的观点和别的地方有所冲突的话，我建议以陈硕老师的实现方式为准

**Comment by GeneralSandman** [comment]
我的天那，感觉跟你都不是在一个层次上的，落后你实在太多了。我的计划是这样的，先用简单的日志组件提供给系统使用，前期先不追求性能；在后期在对多进程日志，多进程日志输出混乱的问题，性能问题进行更新，想让他跑起来。你的log组件有没有比较好的了解教程，我会看看你的，后续对自己的进行优化。
